<?PHP


class Item implements PokemonDataField {

	static $MasterBall = null;
	static $UltraBall = null;
	static $BrightPowder = null;
	static $Greatall = null;
	static $PokeBall = null;
	static $Bicycle = null;
	static $MoonStone = null;
	static $Antidote = null;
	static $BurnHeal = null;
	static $IceHeal = null;
	static $Awakening = null;
	static $ParlyzHeal = null;
	static $FullRestore = null;
	static $MaxPotion = null;
	static $HyperPotion = null;
	static $SuperPotion = null;
	static $Potion = null;
	static $EscapeRope = null;
	static $Repel = null;
	static $MaxElixer = null;
	static $FireStone = null;
	static $ThunderStone = null;
	static $WaterStone = null;
	static $HPUp = null;
	static $Protein = null;
	static $Iron = null;
	static $Carbos = null;
	static $LuckyPunch = null;
	static $Calcium = null;
	static $RareCandy = null;
	static $XAccuracy = null;
	static $LeafStone = null;
	static $MetalPowder = null;
	static $Nugget = null;
	static $PokeDoll = null;
	static $FullHeal = null;
	static $Revive = null;
	static $MaxRevive = null;
	static $GuardSpec = null;
	static $SuperRepel = null;
	static $MaxRepel = null;
	static $DireHit = null;
	static $FreshWater = null;
	static $SodaPop = null;
	static $Lemonade = null;
	static $XAttack = null;
	static $XDefend = null;
	static $XSpeed = null;
	static $XSpecial = null;
	static $CoinCase = null;
	static $Itemfinder = null;
	static $ExpShare = null;
	static $OldRod = null;
	static $GoodRod = null;
	static $SilverLeaf = null;
	static $SuperRod = null;
	static $PPUp = null;
	static $Ether = null;
	static $MaxEther = null;
	static $Elixer = null;
	static $RedScale = null;
	static $SecretPotion = null;
	static $SSTicket = null;
	static $MysteryEgg = null;
	static $ClearBell = null;
	static $SilverWing = null;
	static $MoomooMilk = null;
	static $QuickClaw = null;
	static $PSNCureBerry = null;
	static $GoldLeaf = null;
	static $SoftSand = null;
	static $SharpBeak = null;
	static $PRZCureBerry = null;
	static $BurntBerry = null;
	static $IceBerry = null;
	static $PoisonBarb = null;
	static $KingsRock = null;
	static $BitterBerry = null;
	static $MintBerry = null;
	static $RedApricorn = null;
	static $TinyMushroom = null;
	static $BigMushroom = null;
	static $SilverPowder = null;
	static $BluApricorn = null;
	static $AmuletCoin = null;
	static $YlwApricorn = null;
	static $GrnApricorn = null;
	static $CleanseTag = null;
	static $MysticWater = null;
	static $TwistedSpoon = null;
	static $WhtApricorn = null;
	static $BlackBelt = null;
	static $BlkApricorn = null;
	static $PnkApricorn = null;
	static $BlackGlasses = null;
	static $SlowpokeTail = null;
	static $PinkBow = null;
	static $Stick = null;
	static $SmokeBall = null;
	static $NeverMeltIce = null;
	static $Magnet = null;
	static $MiracleBerry = null;
	static $Pearl = null;
	static $BigPearl = null;
	static $Everstone = null;
	static $SpellTag = null;
	static $RageCandyBar = null;
	static $GSBall = null;
	static $BlueCard = null;
	static $MiracleSeed = null;
	static $ThickClub = null;
	static $FocusBand = null;
	static $EnergyPowder = null;
	static $EnergyRoot = null;
	static $HealPowder = null;
	static $RevivalHerb = null;
	static $HardStone = null;
	static $LuckyEgg = null;
	static $CardKey = null;
	static $MachinePart = null;
	static $EggTicket = null;
	static $LostItem = null;
	static $Stardust = null;
	static $StarPiece = null;
	static $BasementKey = null;
	static $Pass = null;
	static $Charcoal = null;
	static $BerryJuice = null;
	static $ScopeLens = null;
	static $MetalCoat = null;
	static $DragonFang = null;
	static $Leftovers = null;
	static $MysteryBerry = null;
	static $DragonScale = null;
	static $BerserkGene = null;
	static $SacredAsh = null;
	static $HeavyBall = null;
	static $FlowerMail = null;
	static $LevelBall = null;
	static $LureBall = null;
	static $FastBall = null;
	static $LightBall = null;
	static $FriendBall = null;
	static $MoonBall = null;
	static $LoveBall = null;
	static $NormalBox = null;
	static $GorgeousBox = null;
	static $SunStone = null;
	static $PolkadotBow = null;
	static $UpGrade = null;
	static $Berry = null;
	static $GoldBerry = null;
	static $SquirtBottle = null;
	static $ParkBall = null;
	static $RainbowWing = null;
	static $BrickPiece = null;
	static $SurfMail = null;
	static $Litebluemail = null;
	static $Portraitmail = null;
	static $LovelyMail = null;
	static $EonMail = null;
	static $MorphMail = null;
	static $BlueskyMail = null;
	static $MusicMail = null;
	static $MirageMail = null;
	static $TM01 = null;
	static $TM02 = null;
	static $TM03 = null;
	static $TM04 = null;
	static $TM05 = null;
	static $TM06 = null;
	static $TM07 = null;
	static $TM08 = null;
	static $TM09 = null;
	static $TM10 = null;
	static $TM11 = null;
	static $TM12 = null;
	static $TM13 = null;
	static $TM14 = null;
	static $TM15 = null;
	static $TM16 = null;
	static $TM17 = null;
	static $TM18 = null;
	static $TM19 = null;
	static $TM20 = null;
	static $TM21 = null;
	static $TM22 = null;
	static $TM23 = null;
	static $TM24 = null;
	static $TM25 = null;
	static $TM26 = null;
	static $TM27 = null;
	static $TM28 = null;
	static $TM29 = null;
	static $TM30 = null;
	static $TM31 = null;
	static $TM32 = null;
	static $TM33 = null;
	static $TM34 = null;
	static $TM35 = null;
	static $TM36 = null;
	static $TM37 = null;
	static $TM38 = null;
	static $TM39 = null;
	static $TM40 = null;
	static $TM41 = null;
	static $TM42 = null;
	static $TM43 = null;
	static $TM44 = null;
	static $TM45 = null;
	static $TM46 = null;
	static $TM47 = null;
	static $TM48 = null;
	static $TM49 = null;
	static $TM50 = null;
	static $HM01 = null;
	static $HM02 = null;
	static $HM03 = null;
	static $HM04 = null;
	static $HM05 = null;
	static $HM06 = null;
	static $HM07 = null;
	static $HM08 = null;
	static $HM09 = null;
	static $HM10 = null;
	static $HM11 = null;
	static $HM12 = null;

	private $hexCode;
	private $name;

	public static $map;

	public function __construct($hexCode, $name) {
		$this->hexCode = $hexCode;
		$this->name = $name;
	}
	public static function init () {
		self::$MasterBall  	= new Item("0x01", "Master Ball");
		self::$UltraBall  	= new Item("0x02", "Ultra Ball");
		self::$BrightPowder  	= new Item("0x03", "BrightPowder");
		self::$Greatall  	= new Item("0x04", "Great Ball");
		self::$PokeBall  	= new Item("0x05", "Poké Ball");
		self::$Bicycle  	= new Item("0x06", "Bicycle");
		self::$MoonStone  	= new Item("0x08", "Moon Stone");
		self::$Antidote  	= new Item("0x09", "Antidote");
		self::$BurnHeal  	= new Item("0x0A", "Burn Heal");
		self::$IceHeal  	= new Item("0x0B", "Ice Heal");
		self::$Awakening  	= new Item("0x0C", "Awakening");
		self::$ParlyzHeal  	= new Item("0x0D", "Parlyz Heal");
		self::$FullRestore  	= new Item("0x0E", "Full Restore");
		self::$MaxPotion  	= new Item("0x0F", "Max Potion");
		self::$HyperPotion  	= new Item("0x10", "Hyper Potion");
		self::$SuperPotion  	= new Item("0x11", "Super Potion");
		self::$Potion  	= new Item("0x12", "Potion");
		self::$EscapeRope  	= new Item("0x13", "Escape Rope");
		self::$Repel  	= new Item("0x14", "Repel");
		self::$MaxElixer  	= new Item("0x15", "Max Elixer");
		self::$FireStone  	= new Item("0x16", "Fire Stone");
		self::$ThunderStone  	= new Item("0x17", "Thunder Stone");
		self::$WaterStone  	= new Item("0x18", "Water Stone");
		self::$HPUp  	= new Item("0x1A", "HP Up");
		self::$Protein  	= new Item("0x1B", "Protein");
		self::$Iron  	= new Item("0x1C", "Iron");
		self::$Carbos  	= new Item("0x1D", "Carbos");
		self::$LuckyPunch  	= new Item("0x1E", "Lucky Punch");
		self::$Calcium  	= new Item("0x1F", "Calcium");
		self::$RareCandy  	= new Item("0x20", "Rare Candy");
		self::$XAccuracy  	= new Item("0x21", "X Accuracy");
		self::$LeafStone  	= new Item("0x22", "Leaf Stone");
		self::$MetalPowder  	= new Item("0x23", "Metal Powder");
		self::$Nugget  	= new Item("0x24", "Nugget");
		self::$PokeDoll  	= new Item("0x25", "Poké Doll");
		self::$FullHeal  	= new Item("0x26", "Full Heal");
		self::$Revive  	= new Item("0x27", "Revive");
		self::$MaxRevive  	= new Item("0x28", "Max Revive");
		self::$GuardSpec  	= new Item("0x29", "Guard Spec.");
		self::$SuperRepel  	= new Item("0x2A", "Super Repel");
		self::$MaxRepel  	= new Item("0x2B", "Max Repel");
		self::$DireHit  	= new Item("0x2C", "Dire Hit");
		self::$FreshWater  	= new Item("0x2E", "Fresh Water");
		self::$SodaPop  	= new Item("0x2F", "Soda Pop");
		self::$Lemonade  	= new Item("0x30", "Lemonade");
		self::$XAttack  	= new Item("0x31", "X Attack");
		self::$XDefend  	= new Item("0x33", "X Defend");
		self::$XSpeed  	= new Item("0x34", "X Speed");
		self::$XSpecial  	= new Item("0x35", "X Special");
		self::$CoinCase  	= new Item("0x36", "Coin Case");
		self::$Itemfinder  	= new Item("0x37", "Itemfinder");
		self::$ExpShare  	= new Item("0x39", "Exp Share");
		self::$OldRod  	= new Item("0x3A", "Old Rod");
		self::$GoodRod  	= new Item("0x3B", "Good Rod");
		self::$SilverLeaf  	= new Item("0x3C", "Silver Leaf");
		self::$SuperRod  	= new Item("0x3D", "Super Rod");
		self::$PPUp  	= new Item("0x3E", "PP Up");
		self::$Ether  	= new Item("0x3F", "Ether");
		self::$MaxEther  	= new Item("0x40", "Max Ether");
		self::$Elixer  	= new Item("0x41", "Elixer");
		self::$RedScale  	= new Item("0x42", "Red Scale");
		self::$SecretPotion  	= new Item("0x43", "SecretPotion");
		self::$SSTicket  	= new Item("0x44", "S.S. Ticket");
		self::$MysteryEgg  	= new Item("0x45", "Mystery Egg");
		self::$ClearBell  	= new Item("0x46", "Clear Bell*");
		self::$SilverWing  	= new Item("0x47", "Silver Wing");
		self::$MoomooMilk  	= new Item("0x48", "Moomoo Milk");
		self::$QuickClaw  	= new Item("0x49", "Quick Claw");
		self::$PSNCureBerry  	= new Item("0x4A", "PSNCureBerry");
		self::$GoldLeaf  	= new Item("0x4B", "Gold Leaf");
		self::$SoftSand  	= new Item("0x4C", "Soft Sand");
		self::$SharpBeak  	= new Item("0x4D", "Sharp Beak");
		self::$PRZCureBerry  	= new Item("0x4E", "PRZCureBerry");
		self::$BurntBerry  	= new Item("0x4F", "Burnt Berry");
		self::$IceBerry  	= new Item("0x50", "Ice Berry");
		self::$PoisonBarb  	= new Item("0x51", "Poison Barb");
		self::$KingsRock  	= new Item("0x52", "King's Rock");
		self::$BitterBerry  	= new Item("0x53", "Bitter Berry");
		self::$MintBerry  	= new Item("0x54", "Mint Berry");
		self::$RedApricorn  	= new Item("0x55", "Red Apricorn");
		self::$TinyMushroom  	= new Item("0x56", "TinyMushroom");
		self::$BigMushroom  	= new Item("0x57", "Big Mushroom");
		self::$SilverPowder  	= new Item("0x58", "SilverPowder");
		self::$BluApricorn  	= new Item("0x59", "Blu Apricorn");
		self::$AmuletCoin  	= new Item("0x5B", "Amulet Coin");
		self::$YlwApricorn  	= new Item("0x5C", "Ylw Apricorn");
		self::$GrnApricorn  	= new Item("0x5D", "Grn Apricorn");
		self::$CleanseTag  	= new Item("0x5E", "Cleanse Tag");
		self::$MysticWater  	= new Item("0x5F", "Mystic Water");
		self::$TwistedSpoon  	= new Item("0x60", "TwistedSpoon");
		self::$WhtApricorn  	= new Item("0x61", "Wht Apricorn");
		self::$BlackBelt  	= new Item("0x62", "Black Belt");
		self::$BlkApricorn  	= new Item("0x63", "Blk Apricorn");
		self::$PnkApricorn  	= new Item("0x65", "Pnk Apricorn");
		self::$BlackGlasses  	= new Item("0x66", "BlackGlasses");
		self::$SlowpokeTail  	= new Item("0x67", "SlowpokeTail");
		self::$PinkBow  	= new Item("0x68", "Pink Bow");
		self::$Stick  	= new Item("0x69", "Stick");
		self::$SmokeBall  	= new Item("0x6A", "Smoke Ball");
		self::$NeverMeltIce  	= new Item("0x6B", "NeverMeltIce");
		self::$Magnet  	= new Item("0x6C", "Magnet");
		self::$MiracleBerry  	= new Item("0x6D", "MiracleBerry");
		self::$Pearl  	= new Item("0x6E", "Pearl");
		self::$BigPearl  	= new Item("0x6F", "Big Pearl");
		self::$Everstone  	= new Item("0x70", "Everstone");
		self::$SpellTag  	= new Item("0x71", "Spell Tag");
		self::$RageCandyBar  	= new Item("0x72", "RageCandyBar");
		self::$GSBall  	= new Item("0x73", "GS Ball*");
		self::$BlueCard  	= new Item("0x74", "Blue Card*");
		self::$MiracleSeed  	= new Item("0x75", "Miracle Seed");
		self::$ThickClub  	= new Item("0x76", "Thick Club");
		self::$FocusBand  	= new Item("0x77", "Focus Band");
		self::$EnergyPowder  	= new Item("0x79", "EnergyPowder");
		self::$EnergyRoot  	= new Item("0x7A", "Energy Root");
		self::$HealPowder  	= new Item("0x7B", "Heal Powder");
		self::$RevivalHerb  	= new Item("0x7C", "Revival Herb");
		self::$HardStone  	= new Item("0x7D", "Hard Stone");
		self::$LuckyEgg  	= new Item("0x7E", "Lucky Egg");
		self::$CardKey  	= new Item("0x7F", "Card Key");
		self::$MachinePart  	= new Item("0x80", "Machine Part");
		self::$EggTicket  	= new Item("0x81", "Egg Ticket*");
		self::$LostItem  	= new Item("0x82", "Lost Item");
		self::$Stardust  	= new Item("0x83", "Stardust");
		self::$StarPiece  	= new Item("0x84", "Star Piece");
		self::$BasementKey  	= new Item("0x85", "Basement Key");
		self::$Pass  	= new Item("0x86", "Pass");
		self::$Charcoal  	= new Item("0x8A", "Charcoal");
		self::$BerryJuice  	= new Item("0x8B", "Berry Juice");
		self::$ScopeLens  	= new Item("0x8C", "Scope Lens");
		self::$MetalCoat  	= new Item("0x8F", "Metal Coat");
		self::$DragonFang  	= new Item("0x90", "Dragon Fang");
		self::$Leftovers  	= new Item("0x92", "Leftovers");
		self::$MysteryBerry  	= new Item("0x96", "MysteryBerry");
		self::$DragonScale  	= new Item("0x97", "Dragon Scale");
		self::$BerserkGene  	= new Item("0x98", "Berserk Gene");
		self::$SacredAsh  	= new Item("0x9C", "Sacred Ash");
		self::$HeavyBall  	= new Item("0x9D", "Heavy Ball");
		self::$FlowerMail  	= new Item("0x9E", "Flower Mail");
		self::$LevelBall  	= new Item("0x9F", "Level Ball");
		self::$LureBall  	= new Item("0xA0", "Lure Ball");
		self::$FastBall  	= new Item("0xA1", "Fast Ball");
		self::$LightBall  	= new Item("0xA3", "Light Ball");
		self::$FriendBall  	= new Item("0xA4", "Friend Ball");
		self::$MoonBall  	= new Item("0xA5", "Moon Ball");
		self::$LoveBall  	= new Item("0xA6", "Love Ball");
		self::$NormalBox  	= new Item("0xA7", "Normal Box");
		self::$GorgeousBox  	= new Item("0xA8", "Gorgeous Box");
		self::$SunStone  	= new Item("0xA9", "Sun Stone");
		self::$PolkadotBow  	= new Item("0xAA", "Polkadot Bow");
		self::$UpGrade  	= new Item("0xAC", "Up-Grade");
		self::$Berry  	= new Item("0xAD", "Berry");
		self::$GoldBerry  	= new Item("0xAE", "Gold Berry");
		self::$SquirtBottle  	= new Item("0xAF", "SquirtBottle");
		self::$ParkBall  	= new Item("0xB1", "Park Ball");
		self::$RainbowWing  	= new Item("0xB2", "Rainbow Wing");
		self::$BrickPiece  	= new Item("0xB4", "Brick Piece");
		self::$SurfMail  	= new Item("0xB5", "Surf Mail");
		self::$Litebluemail  	= new Item("0xB6", "Litebluemail");
		self::$Portraitmail  	= new Item("0xB7", "Portraitmail");
		self::$LovelyMail  	= new Item("0xB8", "Lovely Mail");
		self::$EonMail  	= new Item("0xB9", "Eon Mail");
		self::$MorphMail  	= new Item("0xBA", "Morph Mail");
		self::$BlueskyMail  	= new Item("0xBB", "Bluesky Mail");
		self::$MusicMail  	= new Item("0xBC", "Music Mail");
		self::$MirageMail  	= new Item("0xBD", "Mirage Mail");
		self::$TM01  	= new Item("0xBF", "TM01");
		self::$TM02  	= new Item("0xC0", "TM02");
		self::$TM03  	= new Item("0xC1", "TM03");
		self::$TM04  	= new Item("0xC2", "TM04");
		self::$TM05  	= new Item("0xC4", "TM05");
		self::$TM06  	= new Item("0xC5", "TM06");
		self::$TM07  	= new Item("0xC6", "TM07");
		self::$TM08  	= new Item("0xC7", "TM08");
		self::$TM09  	= new Item("0xC8", "TM09");
		self::$TM10  	= new Item("0xC9", "TM10");
		self::$TM11  	= new Item("0xCA", "TM11");
		self::$TM12  	= new Item("0xCB", "TM12");
		self::$TM13  	= new Item("0xCC", "TM13");
		self::$TM14  	= new Item("0xCD", "TM14");
		self::$TM15  	= new Item("0xCE", "TM15");
		self::$TM16  	= new Item("0xCF", "TM16");
		self::$TM17  	= new Item("0xD0", "TM17");
		self::$TM18  	= new Item("0xD1", "TM18");
		self::$TM19  	= new Item("0xD2", "TM19");
		self::$TM20  	= new Item("0xD3", "TM20");
		self::$TM21  	= new Item("0xD4", "TM21");
		self::$TM22  	= new Item("0xD5", "TM22");
		self::$TM23  	= new Item("0xD6", "TM23");
		self::$TM24  	= new Item("0xD7", "TM24");
		self::$TM25  	= new Item("0xD8", "TM25");
		self::$TM26  	= new Item("0xD9", "TM26");
		self::$TM27  	= new Item("0xDA", "TM27");
		self::$TM28  	= new Item("0xDB", "TM28");
		self::$TM29  	= new Item("0xDD", "TM29");
		self::$TM30  	= new Item("0xDE", "TM30");
		self::$TM31  	= new Item("0xDF", "TM31");
		self::$TM32  	= new Item("0xE0", "TM32");
		self::$TM33  	= new Item("0xE1", "TM33");
		self::$TM34  	= new Item("0xE2", "TM34");
		self::$TM35  	= new Item("0xE3", "TM35");
		self::$TM36  	= new Item("0xE4", "TM36");
		self::$TM37  	= new Item("0xE5", "TM37");
		self::$TM38  	= new Item("0xE6", "TM38");
		self::$TM39  	= new Item("0xE7", "TM39");
		self::$TM40  	= new Item("0xE8", "TM40");
		self::$TM41  	= new Item("0xE9", "TM41");
		self::$TM42  	= new Item("0xEA", "TM42");
		self::$TM43  	= new Item("0xEB", "TM43");
		self::$TM44  	= new Item("0xEC", "TM44");
		self::$TM45  	= new Item("0xED", "TM45");
		self::$TM46  	= new Item("0xEE", "TM46");
		self::$TM47  	= new Item("0xEF", "TM47");
		self::$TM48  	= new Item("0xF0", "TM48");
		self::$TM49  	= new Item("0xF1", "TM49");
		self::$TM50  	= new Item("0xF2", "TM50");
		self::$HM01  	= new Item("0xF3", "HM01");
		self::$HM02  	= new Item("0xF4", "HM02");
		self::$HM03  	= new Item("0xF5", "HM03");
		self::$HM04  	= new Item("0xF6", "HM04");
		self::$HM05  	= new Item("0xF7", "HM05");
		self::$HM06  	= new Item("0xF8", "HM06");
		self::$HM07  	= new Item("0xF9", "HM07");
		self::$HM08  	= new Item("0xFA", "HM08");
		self::$HM09  	= new Item("0xFB", "HM09");
		self::$HM10  	= new Item("0xFC", "HM10");
		self::$HM11  	= new Item("0xFD", "HM11");
		self::$HM12  	= new Item("0xFE", "HM12");

        self::$map = array (
            "MasterBall" => self::$MasterBall,
			"UltraBall" => self::$UltraBall,
			"BrightPowder" => self::$BrightPowder,
			"Greatall" => self::$Greatall,
			"PokeBall" => self::$PokeBall,
			"Bicycle" => self::$Bicycle,
			"MoonStone" => self::$MoonStone,
			"Antidote" => self::$Antidote,
			"BurnHeal" => self::$BurnHeal,
			"IceHeal" => self::$IceHeal,
			"Awakening" => self::$Awakening,
			"ParlyzHeal" => self::$ParlyzHeal,
			"FullRestore" => self::$FullRestore,
			"MaxPotion" => self::$MaxPotion,
			"HyperPotion" => self::$HyperPotion,
			"SuperPotion" => self::$SuperPotion,
			"Potion" => self::$Potion,
			"EscapeRope" => self::$EscapeRope,
			"Repel" => self::$Repel,
			"MaxElixer" => self::$MaxElixer,
			"FireStone" => self::$FireStone,
			"ThunderStone" => self::$ThunderStone,
			"WaterStone" => self::$WaterStone,
			"HPUp" => self::$HPUp,
			"Protein" => self::$Protein,
			"Iron" => self::$Iron,
			"Carbos" => self::$Carbos,
			"LuckyPunch" => self::$LuckyPunch,
			"Calcium" => self::$Calcium,
			"RareCandy" => self::$RareCandy,
			"XAccuracy" => self::$XAccuracy,
			"LeafStone" => self::$LeafStone,
			"MetalPowder" => self::$MetalPowder,
			"Nugget" => self::$Nugget,
			"PokeDoll" => self::$PokeDoll,
			"FullHeal" => self::$FullHeal,
			"Revive" => self::$Revive,
			"MaxRevive" => self::$MaxRevive,
			"GuardSpec" => self::$GuardSpec,
			"SuperRepel" => self::$SuperRepel,
			"MaxRepel" => self::$MaxRepel,
			"DireHit" => self::$DireHit,
			"FreshWater" => self::$FreshWater,
			"SodaPop" => self::$SodaPop,
			"Lemonade" => self::$Lemonade,
			"XAttack" => self::$XAttack,
			"XDefend" => self::$XDefend,
			"XSpeed" => self::$XSpeed,
			"XSpecial" => self::$XSpecial,
			"CoinCase" => self::$CoinCase,
			"Itemfinder" => self::$Itemfinder,
			"ExpShare" => self::$ExpShare,
			"OldRod" => self::$OldRod,
			"GoodRod" => self::$GoodRod,
			"SilverLeaf" => self::$SilverLeaf,
			"SuperRod" => self::$SuperRod,
			"PPUp" => self::$PPUp,
			"Ether" => self::$Ether,
			"MaxEther" => self::$MaxEther,
			"Elixer" => self::$Elixer,
			"RedScale" => self::$RedScale,
			"SecretPotion" => self::$SecretPotion,
			"SSTicket" => self::$SSTicket,
			"MysteryEgg" => self::$MysteryEgg,
			"ClearBell" => self::$ClearBell,
			"SilverWing" => self::$SilverWing,
			"MoomooMilk" => self::$MoomooMilk,
			"QuickClaw" => self::$QuickClaw,
			"PSNCureBerry" => self::$PSNCureBerry,
			"GoldLeaf" => self::$GoldLeaf,
			"SoftSand" => self::$SoftSand,
			"SharpBeak" => self::$SharpBeak,
			"PRZCureBerry" => self::$PRZCureBerry,
			"BurntBerry" => self::$BurntBerry,
			"IceBerry" => self::$IceBerry,
			"PoisonBarb" => self::$PoisonBarb,
			"KingsRock" => self::$KingsRock,
			"BitterBerry" => self::$BitterBerry,
			"MintBerry" => self::$MintBerry,
			"RedApricorn" => self::$RedApricorn,
			"TinyMushroom" => self::$TinyMushroom,
			"BigMushroom" => self::$BigMushroom,
			"SilverPowder" => self::$SilverPowder,
			"BluApricorn" => self::$BluApricorn,
			"AmuletCoin" => self::$AmuletCoin,
			"YlwApricorn" => self::$YlwApricorn,
			"GrnApricorn" => self::$GrnApricorn,
			"CleanseTag" => self::$CleanseTag,
			"MysticWater" => self::$MysticWater,
			"TwistedSpoon" => self::$TwistedSpoon,
			"WhtApricorn" => self::$WhtApricorn,
			"BlackBelt" => self::$BlackBelt,
			"BlkApricorn" => self::$BlkApricorn,
			"PnkApricorn" => self::$PnkApricorn,
			"BlackGlasses" => self::$BlackGlasses,
			"SlowpokeTail" => self::$SlowpokeTail,
			"PinkBow" => self::$PinkBow,
			"Stick" => self::$Stick,
			"SmokeBall" => self::$SmokeBall,
			"NeverMeltIce" => self::$NeverMeltIce,
			"Magnet" => self::$Magnet,
			"MiracleBerry" => self::$MiracleBerry,
			"Pearl" => self::$Pearl,
			"BigPearl" => self::$BigPearl,
			"Everstone" => self::$Everstone,
			"SpellTag" => self::$SpellTag,
			"RageCandyBar" => self::$RageCandyBar,
			"GSBall" => self::$GSBall,
			"BlueCard" => self::$BlueCard,
			"MiracleSeed" => self::$MiracleSeed,
			"ThickClub" => self::$ThickClub,
			"FocusBand" => self::$FocusBand,
			"EnergyPowder" => self::$EnergyPowder,
			"EnergyRoot" => self::$EnergyRoot,
			"HealPowder" => self::$HealPowder,
			"RevivalHerb" => self::$RevivalHerb,
			"HardStone" => self::$HardStone,
			"LuckyEgg" => self::$LuckyEgg,
			"CardKey" => self::$CardKey,
			"MachinePart" => self::$MachinePart,
			"EggTicket" => self::$EggTicket,
			"LostItem" => self::$LostItem,
			"Stardust" => self::$Stardust,
			"StarPiece" => self::$StarPiece,
			"BasementKey" => self::$BasementKey,
			"Pass" => self::$Pass,
			"Charcoal" => self::$Charcoal,
			"BerryJuice" => self::$BerryJuice,
			"ScopeLens" => self::$ScopeLens,
			"MetalCoat" => self::$MetalCoat,
			"DragonFang" => self::$DragonFang,
			"Leftovers" => self::$Leftovers,
			"MysteryBerry" => self::$MysteryBerry,
			"DragonScale" => self::$DragonScale,
			"BerserkGene" => self::$BerserkGene,
			"SacredAsh" => self::$SacredAsh,
			"HeavyBall" => self::$HeavyBall,
			"FlowerMail" => self::$FlowerMail,
			"LevelBall" => self::$LevelBall,
			"LureBall" => self::$LureBall,
			"FastBall" => self::$FastBall,
			"LightBall" => self::$LightBall,
			"FriendBall" => self::$FriendBall,
			"MoonBall" => self::$MoonBall,
			"LoveBall" => self::$LoveBall,
			"NormalBox" => self::$NormalBox,
			"GorgeousBox" => self::$GorgeousBox,
			"SunStone" => self::$SunStone,
			"PolkadotBow" => self::$PolkadotBow,
			"UpGrade" => self::$UpGrade,
			"Berry" => self::$Berry,
			"GoldBerry" => self::$GoldBerry,
			"SquirtBottle" => self::$SquirtBottle,
			"ParkBall" => self::$ParkBall,
			"RainbowWing" => self::$RainbowWing,
			"BrickPiece" => self::$BrickPiece,
			"SurfMail" => self::$SurfMail,
			"Litebluemail" => self::$Litebluemail,
			"Portraitmail" => self::$Portraitmail,
			"LovelyMail" => self::$LovelyMail,
			"EonMail" => self::$EonMail,
			"MorphMail" => self::$MorphMail,
			"BlueskyMail" => self::$BlueskyMail,
			"MusicMail" => self::$MusicMail,
			"MirageMail" => self::$MirageMail,
			"TM01" => self::$TM01,
			"TM02" => self::$TM02,
			"TM03" => self::$TM03,
			"TM04" => self::$TM04,
			"TM05" => self::$TM05,
			"TM06" => self::$TM06,
			"TM07" => self::$TM07,
			"TM08" => self::$TM08,
			"TM09" => self::$TM09,
			"TM10" => self::$TM10,
			"TM11" => self::$TM11,
			"TM12" => self::$TM12,
			"TM13" => self::$TM13,
			"TM14" => self::$TM14,
			"TM15" => self::$TM15,
			"TM16" => self::$TM16,
			"TM17" => self::$TM17,
			"TM18" => self::$TM18,
			"TM19" => self::$TM19,
			"TM20" => self::$TM20,
			"TM21" => self::$TM21,
			"TM22" => self::$TM22,
			"TM23" => self::$TM23,
			"TM24" => self::$TM24,
			"TM25" => self::$TM25,
			"TM26" => self::$TM26,
			"TM27" => self::$TM27,
			"TM28" => self::$TM28,
			"TM29" => self::$TM29,
			"TM30" => self::$TM30,
			"TM31" => self::$TM31,
			"TM32" => self::$TM32,
			"TM33" => self::$TM33,
			"TM34" => self::$TM34,
			"TM35" => self::$TM35,
			"TM36" => self::$TM36,
			"TM37" => self::$TM37,
			"TM38" => self::$TM38,
			"TM39" => self::$TM39,
			"TM40" => self::$TM40,
			"TM41" => self::$TM41,
			"TM42" => self::$TM42,
			"TM43" => self::$TM43,
			"TM44" => self::$TM44,
			"TM45" => self::$TM45,
			"TM46" => self::$TM46,
			"TM47" => self::$TM47,
			"TM48" => self::$TM48,
			"TM49" => self::$TM49,
			"TM50" => self::$TM50,
			"HM01" => self::$HM01,
			"HM02" => self::$HM02,
			"HM03" => self::$HM03,
			"HM04" => self::$HM04,
			"HM05" => self::$HM05,
			"HM06" => self::$HM06,
			"HM07" => self::$HM07,
			"HM08" => self::$HM08,
			"HM09" => self::$HM09,
			"HM10" => self::$HM10,
			"HM11" => self::$HM11,
			"HM12" => self::$HM12
        );
	}
	public static function get($element) {
        if($element == null)
            return null;
        return self::$map[$element];
    }


    public function getHex(){
    	return PokemonData::hex($this->hexCode);
    }

    public function getName(){
    	return $this->name;
    }
}
Item::init();