<?PHP


class Move implements PokemonDataField {

	static $Nothing = null;
	static $Pound = null;
	static $KarateChop = null;
	static $DoubleSlap = null;
	static $CometPunch = null;
	static $MegaPunch = null;
	static $PayDay = null;
	static $FirePunch = null;
	static $IcePunch = null;
	static $ThunderPunch = null;
	static $Gust = null;
	static $WingAttack = null;
	static $Whirlwind = null;
	static $Fly = null;
	static $Bind = null;
	static $Slam = null;
	static $VineWhip = null;
	static $Stomp = null;
	static $DoubleKick = null;
	static $MegaKick = null;
	static $JumpKIck = null;
	static $RollingKick = null;
	static $SandAttack = null;
	static $Headbutt = null;
	static $HornAttack = null;
	static $FuryAttack = null;
	static $HornDrill = null;
	static $Tackle = null;
	static $Bodyslam = null;
	static $Wrap = null;
	static $TakeDown = null;
	static $Trash = null;
	static $DoubleEdge = null;
	static $TailWhip = null;
	static $PoisonSting = null;
	static $TwinNeedle = null;
	static $PinMissle = null;
	static $Leer = null;
	static $Bite = null;
	static $Growl = null;
	static $Roar = null;
	static $SuperSonic = null;
	static $SonicBoom = null;
	static $Disable = null;
	static $Acid = null;
	static $Ember = null;
	static $FlameThrower = null;
	static $Mist = null;
	static $WaterGun = null;
	static $HydroPump = null;
	static $Surf = null;
	static $IceBeam = null;
	static $Blizzard = null;
	static $PsyBeam = null;
	static $BubbleBeam = null;
	static $AuroraBeam = null;
	static $HyperBeam = null;
	static $Peck = null;
	static $DrillPeck = null;
	static $Submission = null;
	static $LowKick = null;
	static $Counter = null;
	static $SesmicToss = null;
	static $Strength = null;
	static $Absorb = null;
	static $MegaDrain = null;
	static $LeechSeed = null;
	static $Growth = null;
	static $RazorWind = null;
	static $SolarBeam = null;
	static $PoisonPowder = null;
	static $StunSpore = null;
	static $SleepPowder = null;
	static $PetalDance = null;
	static $StringShot = null;
	static $DragonRage = null;
	static $FireSpin = null;
	static $ThunderShock = null;
	static $ThunderBolt = null;
	static $ThunderWave = null;
	static $Thunder = null;
	static $RockThrow = null;
	static $EarthQuake = null;
	static $Fissure = null;
	static $Dig = null;
	static $Toxic = null;
	static $Confusion = null;
	static $Psychic = null;
	static $Hypnosis = null;
	static $Meditate = null;
	static $Agility = null;
	static $QuickAttack = null;
	static $Rage = null;
	static $Teleport = null;
	static $NightShade = null;
	static $Mimic = null;
	static $Screech = null;
	static $DoubleTeam = null;
	static $Recover = null;
	static $Harden = null;
	static $Minimized = null;
	static $SmokeScreen = null;
	static $ConfuseRay = null;
	static $WithDraw = null;
	static $DefenceCurl = null;
	static $Barrier = null;
	static $Lightscreen = null;
	static $Haze = null;
	static $Reflect = null;
	static $Focus = null;
	static $Bide = null;
	static $Metronome = null;
	static $MirrorMove = null;
	static $SelfDestruct = null;
	static $EggBomb = null;
	static $Lick = null;
	static $Smog = null;
	static $Sludge = null;
	static $BoneClub = null;
	static $FireBlast = null;
	static $Waterfall = null;
	static $Clamp = null;
	static $Swift = null;
	static $SkullBash = null;
	static $SpikeCannon = null;
	static $Constrict = null;
	static $Amnesia = null;
	static $Kinesis = null;
	static $Softboiled = null;
	static $HiJumpKick = null;
	static $Glare = null;
	static $DreamEater = null;
	static $PoisonGas = null;
	static $Barrage = null;
	static $LeechLife = null;
	static $LovelyKiss = null;
	static $SkyAttack = null;
	static $Transform = null;
	static $Bubble = null;
	static $DizzyPunch = null;
	static $Spore = null;
	static $Flash = null;
	static $Psywave = null;
	static $Splash = null;
	static $AcidArmor = null;
	static $Crabhammer = null;
	static $Explosion = null;
	static $FurySwipe = null;
	static $Bonemerang = null;
	static $Rest = null;
	static $RockSlide = null;
	static $HyperFang = null;
	static $Sharpen = null;
	static $Conversion = null;
	static $TriAttack = null;
	static $SuperFang = null;
	static $Slash = null;
	static $Substitute = null;
	static $Struggle = null;

	private $hexCode;
	private $name;

	public static $map;

	public function __construct($hexCode, $name) {
		$this->hexCode = $hexCode;
		$this->name = $name;
	}
	public static function init () {
		self::$Nothing  	= new Move("0x00", "Nothing");
		self::$Pound  	= new Move("0x01", "Pound");
		self::$KarateChop  	= new Move("0x02", "Karate Chop");
		self::$DoubleSlap  	= new Move("0x03", "Double Slap");
		self::$CometPunch  	= new Move("0x04", "Comet Punch");
		self::$MegaPunch  	= new Move("0x05", "Mega Punch");
		self::$PayDay  	= new Move("0x06", "Pay Day");
		self::$FirePunch  	= new Move("0x07", "Fire Punch");
		self::$IcePunch  	= new Move("0x08", "Ice Punch");
		self::$ThunderPunch  	= new Move("0x09", "Thunder Punch ");
		self::$Gust  	= new Move("0x10", "Gust");
		self::$WingAttack  	= new Move("0x11", "Wing Attack");
		self::$Whirlwind  	= new Move("0x12", "Whirlwind");
		self::$Fly  	= new Move("0x13", "Fly");
		self::$Bind  	= new Move("0x14", "Bind");
		self::$Slam  	= new Move("0x15", "Slam");
		self::$VineWhip  	= new Move("0x16", "Vine Whip");
		self::$Stomp  	= new Move("0x17", "Stomp");
		self::$DoubleKick  	= new Move("0x18", "Double Kick");
		self::$MegaKick  	= new Move("0x19", "Mega KIck");
		self::$JumpKIck  	= new Move("0x1A", "Jump KIck");
		self::$RollingKick  	= new Move("0x1B", "RollingKick");
		self::$SandAttack  	= new Move("0x1C", "Sand Attack");
		self::$Headbutt  	= new Move("0x1D", "Headbutt");
		self::$HornAttack  	= new Move("0x1E", "Horn Attack");
		self::$FuryAttack  	= new Move("0x1F", "Fury Attack");
		self::$HornDrill  	= new Move("0x20", "Horn Drill");
		self::$Tackle  	= new Move("0x21", "Tackle");
		self::$Bodyslam  	= new Move("0x22", "Bodyslam");
		self::$Wrap  	= new Move("0x23", "Wrap");
		self::$TakeDown  	= new Move("0x24", "Take Down ");
		self::$Trash  	= new Move("0x25", "Trash");
		self::$DoubleEdge  	= new Move("0x26", "Double Edge");
		self::$TailWhip  	= new Move("0x27", "Tail Whip");
		self::$PoisonSting  	= new Move("0x28", "Poison Sting");
		self::$TwinNeedle  	= new Move("0x29", "Twin Needle");
		self::$PinMissle  	= new Move("0x2A", "Pin Missle");
		self::$Leer  	= new Move("0x2B", "Leer");
		self::$Bite  	= new Move("0x2C", "Bite");
		self::$Growl  	= new Move("0x2D", "Growl");
		self::$Roar  	= new Move("0x2E", "Roar");
		self::$SuperSonic  	= new Move("0x2F", "SuperSonic");
		self::$SonicBoom  	= new Move("0x30", "Sonic Boom");
		self::$Disable  	= new Move("0x32", "Disable");
		self::$Acid  	= new Move("0x33", "Acid");
		self::$Ember  	= new Move("0x34", "Ember");
		self::$FlameThrower  	= new Move("0x35", "FlameThrower");
		self::$Mist  	= new Move("0x36", "Mist");
		self::$WaterGun  	= new Move("0x37", "Water Gun");
		self::$HydroPump  	= new Move("0x38", "Hydro Pump");
		self::$Surf  	= new Move("0x39", "Surf");
		self::$IceBeam  	= new Move("0x3A", "Ice Beam");
		self::$Blizzard  	= new Move("0x3B", "Blizzard");
		self::$PsyBeam  	= new Move("0x3C", "PsyBeam");
		self::$BubbleBeam  	= new Move("0x3D", "Bubble Beam");
		self::$AuroraBeam  	= new Move("0x3E", "Aurora Beam");
		self::$HyperBeam  	= new Move("0x3F", "Hyper Beam");
		self::$Peck  	= new Move("0x40", "Peck");
		self::$DrillPeck  	= new Move("0x41", "Drill Peck");
		self::$Submission  	= new Move("0x42", "Submission");
		self::$LowKick  	= new Move("0x43", "Low Kick");
		self::$Counter  	= new Move("0x44", "Counter");
		self::$SesmicToss  	= new Move("0x45", "Sesmic Toss");
		self::$Strength  	= new Move("0x46", "Strength");
		self::$Absorb  	= new Move("0x47", "Absorb");
		self::$MegaDrain  	= new Move("0x48", "Mega Drain");
		self::$LeechSeed  	= new Move("0x49", "Leech Seed");
		self::$Growth  	= new Move("0x4A", "Growth");
		self::$RazorWind  	= new Move("0x4B", "Razor Wind");
		self::$SolarBeam  	= new Move("0x4C", "Solar Beam");
		self::$PoisonPowder  	= new Move("0x4D", "Poison Powder");
		self::$StunSpore  	= new Move("0x4E", "Stun Spore");
		self::$SleepPowder  	= new Move("0x4F", "Sleep Powder");
		self::$PetalDance  	= new Move("0x50", "Petal Dance");
		self::$StringShot  	= new Move("0x51", "String Shot");
		self::$DragonRage  	= new Move("0x52", "Dragon Rage");
		self::$FireSpin  	= new Move("0x53", "Fire Spin");
		self::$ThunderShock  	= new Move("0x54", "ThunderShock");
		self::$ThunderBolt  	= new Move("0x55", "ThunderBolt");
		self::$ThunderWave  	= new Move("0x56", "ThunderWave");
		self::$Thunder  	= new Move("0x57", "Thunder");
		self::$RockThrow  	= new Move("0x58", "Rock Throw");
		self::$EarthQuake  	= new Move("0x59", "EarthQuake");
		self::$Fissure  	= new Move("0x5A", "Fissure");
		self::$Dig  	= new Move("0x5B", "Dig");
		self::$Toxic  	= new Move("0x5C", "Toxic");
		self::$Confusion  	= new Move("0x5D", "Confusion");
		self::$Psychic  	= new Move("0x5E", "Psychic");
		self::$Hypnosis  	= new Move("0x5F", "Hypnosis");
		self::$Meditate  	= new Move("0x60", "Meditate");
		self::$Agility  	= new Move("0x61", "Agility");
		self::$QuickAttack  	= new Move("0x62", "Quick Attack");
		self::$Rage  	= new Move("0x63", "Rage");
		self::$Teleport  	= new Move("0x64", "Teleport");
		self::$NightShade  	= new Move("0x65", "Night Shade");
		self::$Mimic  	= new Move("0x66", "Mimic");
		self::$Screech  	= new Move("0x67", "Screech");
		self::$DoubleTeam  	= new Move("0x68", "Double Team");
		self::$Recover  	= new Move("0x69", "Recover");
		self::$Harden  	= new Move("0x6A", "Harden");
		self::$Minimized  	= new Move("0x6B", "Minimized");
		self::$SmokeScreen  	= new Move("0x6C", "Smoke Screen");
		self::$ConfuseRay  	= new Move("0x6D", "Confuse Ray");
		self::$WithDraw  	= new Move("0x6E", "WithDraw");
		self::$DefenceCurl  	= new Move("0x6F", "Defence Curl");
		self::$Barrier  	= new Move("0x70", "Barrier");
		self::$Lightscreen  	= new Move("0x71", "Light screen");
		self::$Haze  	= new Move("0x72", "Haze");
		self::$Reflect  	= new Move("0x73", "Reflect");
		self::$Focus  	= new Move("0x74", "Focus");
		self::$Bide  	= new Move("0x75", "Bide");
		self::$Metronome  	= new Move("0x76", "Metronome");
		self::$MirrorMove  	= new Move("0x77", "Mirror Move");
		self::$SelfDestruct  	= new Move("0x78", "Self Destruct");
		self::$EggBomb  	= new Move("0x79", "Egg Bomb");
		self::$Lick  	= new Move("0x7A", "Lick");
		self::$Smog  	= new Move("0x7B", "Smog");
		self::$Sludge  	= new Move("0x7C", "Sludge");
		self::$BoneClub  	= new Move("0x7D", "Bone Club");
		self::$FireBlast  	= new Move("0x7E", "Fire Blast");
		self::$Waterfall  	= new Move("0x7F", "Waterfall");
		self::$Clamp  	= new Move("0x80", "Clamp");
		self::$Swift  	= new Move("0x81", "Swift");
		self::$SkullBash  	= new Move("0x82", "Skull Bash");
		self::$SpikeCannon  	= new Move("0x83", "Spike Cannon");
		self::$Constrict  	= new Move("0x84", "Constrict");
		self::$Amnesia  	= new Move("0x85", "Amnesia");
		self::$Kinesis  	= new Move("0x86", "Kinesis");
		self::$Softboiled  	= new Move("0x87", "Softboiled");
		self::$HiJumpKick  	= new Move("0x88", "Hi-Jump Kick");
		self::$Glare  	= new Move("0x89", "Glare");
		self::$DreamEater  	= new Move("0x8A", "Dream Eater");
		self::$PoisonGas  	= new Move("0x8B", "Poison Gas");
		self::$Barrage  	= new Move("0x8C", "Barrage");
		self::$LeechLife  	= new Move("0x8D", "Leech Life");
		self::$LovelyKiss  	= new Move("0x8E", "Lovely Kiss");
		self::$SkyAttack  	= new Move("0x8F", "Sky Attack");
		self::$Transform  	= new Move("0x90", "Transform");
		self::$Bubble  	= new Move("0x91", "Bubble");
		self::$DizzyPunch  	= new Move("0x92", "Dizzy Punch");
		self::$Spore  	= new Move("0x93", "Spore");
		self::$Flash  	= new Move("0x94", "Flash");
		self::$Psywave  	= new Move("0x95", "Psywave");
		self::$Splash  	= new Move("0x96", "Splash");
		self::$AcidArmor  	= new Move("0x97", "Acid Armor");
		self::$Crabhammer  	= new Move("0x98", "Crabhammer");
		self::$Explosion  	= new Move("0x99", "Explosion");
		self::$FurySwipe  	= new Move("0x9A", "Fury Swipe");
		self::$Bonemerang  	= new Move("0x9B", "Bonemerang");
		self::$Rest  	= new Move("0x9C", "Rest");
		self::$RockSlide  	= new Move("0x9D", "Rock Slide");
		self::$HyperFang  	= new Move("0x9E", "Hyper Fang");
		self::$Sharpen  	= new Move("0x9F", "Sharpen");
		self::$Conversion  	= new Move("0xA0", "Conversion");
		self::$TriAttack  	= new Move("0xA1", "Tri Attack");
		self::$SuperFang  	= new Move("0xA2", "Super Fang");
		self::$Slash  	= new Move("0xA3", "Slash");
		self::$Substitute  	= new Move("0xA4", "Substitute");
		self::$Struggle  	= new Move("0xA5", "Struggle");

		self::$map = array (
            "Nothing" => self::$Nothing,
			"Pound" => self::$Pound,
			"KarateChop" => self::$KarateChop,
			"DoubleSlap" => self::$DoubleSlap,
			"CometPunch" => self::$CometPunch,
			"MegaPunch" => self::$MegaPunch,
			"PayDay" => self::$PayDay,
			"FirePunch" => self::$FirePunch,
			"IcePunch" => self::$IcePunch,
			"ThunderPunch" => self::$ThunderPunch,
			"Gust" => self::$Gust,
			"WingAttack" => self::$WingAttack,
			"Whirlwind" => self::$Whirlwind,
			"Fly" => self::$Fly,
			"Bind" => self::$Bind,
			"Slam" => self::$Slam,
			"VineWhip" => self::$VineWhip,
			"Stomp" => self::$Stomp,
			"DoubleKick" => self::$DoubleKick,
			"MegaKick" => self::$MegaKick,
			"JumpKIck" => self::$JumpKIck,
			"RollingKick" => self::$RollingKick,
			"SandAttack" => self::$SandAttack,
			"Headbutt" => self::$Headbutt,
			"HornAttack" => self::$HornAttack,
			"FuryAttack" => self::$FuryAttack,
			"HornDrill" => self::$HornDrill,
			"Tackle" => self::$Tackle,
			"Bodyslam" => self::$Bodyslam,
			"Wrap" => self::$Wrap,
			"TakeDown" => self::$TakeDown,
			"Trash" => self::$Trash,
			"DoubleEdge" => self::$DoubleEdge,
			"TailWhip" => self::$TailWhip,
			"PoisonSting" => self::$PoisonSting,
			"TwinNeedle" => self::$TwinNeedle,
			"PinMissle" => self::$PinMissle,
			"Leer" => self::$Leer,
			"Bite" => self::$Bite,
			"Growl" => self::$Growl,
			"Roar" => self::$Roar,
			"SuperSonic" => self::$SuperSonic,
			"SonicBoom" => self::$SonicBoom,
			"Disable" => self::$Disable,
			"Acid" => self::$Acid,
			"Ember" => self::$Ember,
			"FlameThrower" => self::$FlameThrower,
			"Mist" => self::$Mist,
			"WaterGun" => self::$WaterGun,
			"HydroPump" => self::$HydroPump,
			"Surf" => self::$Surf,
			"IceBeam" => self::$IceBeam,
			"Blizzard" => self::$Blizzard,
			"PsyBeam" => self::$PsyBeam,
			"BubbleBeam" => self::$BubbleBeam,
			"AuroraBeam" => self::$AuroraBeam,
			"HyperBeam" => self::$HyperBeam,
			"Peck" => self::$Peck,
			"DrillPeck" => self::$DrillPeck,
			"Submission" => self::$Submission,
			"LowKick" => self::$LowKick,
			"Counter" => self::$Counter,
			"SesmicToss" => self::$SesmicToss,
			"Strength" => self::$Strength,
			"Absorb" => self::$Absorb,
			"MegaDrain" => self::$MegaDrain,
			"LeechSeed" => self::$LeechSeed,
			"Growth" => self::$Growth,
			"RazorWind" => self::$RazorWind,
			"SolarBeam" => self::$SolarBeam,
			"PoisonPowder" => self::$PoisonPowder,
			"StunSpore" => self::$StunSpore,
			"SleepPowder" => self::$SleepPowder,
			"PetalDance" => self::$PetalDance,
			"StringShot" => self::$StringShot,
			"DragonRage" => self::$DragonRage,
			"FireSpin" => self::$FireSpin,
			"ThunderShock" => self::$ThunderShock,
			"ThunderBolt" => self::$ThunderBolt,
			"ThunderWave" => self::$ThunderWave,
			"Thunder" => self::$Thunder,
			"RockThrow" => self::$RockThrow,
			"EarthQuake" => self::$EarthQuake,
			"Fissure" => self::$Fissure,
			"Dig" => self::$Dig,
			"Toxic" => self::$Toxic,
			"Confusion" => self::$Confusion,
			"Psychic" => self::$Psychic,
			"Hypnosis" => self::$Hypnosis,
			"Meditate" => self::$Meditate,
			"Agility" => self::$Agility,
			"QuickAttack" => self::$QuickAttack,
			"Rage" => self::$Rage,
			"Teleport" => self::$Teleport,
			"NightShade" => self::$NightShade,
			"Mimic" => self::$Mimic,
			"Screech" => self::$Screech,
			"DoubleTeam" => self::$DoubleTeam,
			"Recover" => self::$Recover,
			"Harden" => self::$Harden,
			"Minimized" => self::$Minimized,
			"SmokeScreen" => self::$SmokeScreen,
			"ConfuseRay" => self::$ConfuseRay,
			"WithDraw" => self::$WithDraw,
			"DefenceCurl" => self::$DefenceCurl,
			"Barrier" => self::$Barrier,
			"Lightscreen" => self::$Lightscreen,
			"Haze" => self::$Haze,
			"Reflect" => self::$Reflect,
			"Focus" => self::$Focus,
			"Bide" => self::$Bide,
			"Metronome" => self::$Metronome,
			"MirrorMove" => self::$MirrorMove,
			"SelfDestruct" => self::$SelfDestruct,
			"EggBomb" => self::$EggBomb,
			"Lick" => self::$Lick,
			"Smog" => self::$Smog,
			"Sludge" => self::$Sludge,
			"BoneClub" => self::$BoneClub,
			"FireBlast" => self::$FireBlast,
			"Waterfall" => self::$Waterfall,
			"Clamp" => self::$Clamp,
			"Swift" => self::$Swift,
			"SkullBash" => self::$SkullBash,
			"SpikeCannon" => self::$SpikeCannon,
			"Constrict" => self::$Constrict,
			"Amnesia" => self::$Amnesia,
			"Kinesis" => self::$Kinesis,
			"Softboiled" => self::$Softboiled,
			"HiJumpKick" => self::$HiJumpKick,
			"Glare" => self::$Glare,
			"DreamEater" => self::$DreamEater,
			"PoisonGas" => self::$PoisonGas,
			"Barrage" => self::$Barrage,
			"LeechLife" => self::$LeechLife,
			"LovelyKiss" => self::$LovelyKiss,
			"SkyAttack" => self::$SkyAttack,
			"Transform" => self::$Transform,
			"Bubble" => self::$Bubble,
			"DizzyPunch" => self::$DizzyPunch,
			"Spore" => self::$Spore,
			"Flash" => self::$Flash,
			"Psywave" => self::$Psywave,
			"Splash" => self::$Splash,
			"AcidArmor" => self::$AcidArmor,
			"Crabhammer" => self::$Crabhammer,
			"Explosion" => self::$Explosion,
			"FurySwipe" => self::$FurySwipe,
			"Bonemerang" => self::$Bonemerang,
			"Rest" => self::$Rest,
			"RockSlide" => self::$RockSlide,
			"HyperFang" => self::$HyperFang,
			"Sharpen" => self::$Sharpen,
			"Conversion" => self::$Conversion,
			"TriAttack" => self::$TriAttack,
			"SuperFang" => self::$SuperFang,
			"Slash" => self::$Slash,
			"Substitute" => self::$Substitute,
			"Struggle" => self::$Struggle,
        );
	}
	public static function get($element) {
        if($element == null)
            return null;
        return self::$map[$element];
    }


    public function getHex(){
    	return PokemonData::hex($this->hexCode);
    }

    public function getName(){
    	return $this->name;
    }
}
Move::init();