<?PHP


class Species implements PokemonDataField {

	static $Rhydon = null;
	static $Kangaskhan = null;
	static $NidoranM = null;
	static $Clefairy = null;
	static $Spearow = null;
	static $Voltorb = null;
	static $Nidoking = null;
	static $Slowbro = null;
	static $Ivysaur = null;
	static $Exeggutor = null;
	static $Lickitung = null;
	static $Exeggcute = null;
	static $Grimer = null;
	static $Gengar = null;
	static $NidoranF = null;
	static $Nidoqueen = null;
	static $Cubone = null;
	static $Rhyhorn = null;
	static $Lapras = null;
	static $Arcanine = null;
	static $Mew = null;
	static $Gyarados = null;
	static $Shellder = null;
	static $Tentacool = null;
	static $Gastly = null;
	static $Scyther = null;
	static $Staryu = null;
	static $Blastoise = null;
	static $Pinsir = null;
	static $Tangela = null;
	static $Growlithe = null;
	static $Onix = null;
	static $Fearow = null;
	static $Pidgey = null;
	static $Slowpoke = null;
	static $Kadabra = null;
	static $Graveler = null;
	static $Chansey = null;
	static $Machoke = null;
	static $MrMime = null;
	static $Hitmonlee = null;
	static $Hitmonchan = null;
	static $Arbok = null;
	static $Parasect = null;
	static $Psyduck = null;
	static $Drowzee = null;
	static $Golem = null;
	static $Magmar = null;
	static $Electabuzz = null;
	static $Magneton = null;
	static $Koffing = null;
	static $Mankey = null;
	static $Seel = null;
	static $Diglett = null;
	static $Tauros = null;
	static $Farfetchd = null;
	static $Venonat = null;
	static $Dragonite = null;
	static $Doduo = null;
	static $Poliwag = null;
	static $Jynx = null;
	static $Moltres = null;
	static $Articuno = null;
	static $Zapdos = null;
	static $Ditto = null;
	static $Meowth = null;
	static $Krabby = null;
	static $Vulpix = null;
	static $Ninetales = null;
	static $Pikachu = null;
	static $Raichu = null;
	static $Dratini = null;
	static $Dragonair = null;
	static $Kabuto = null;
	static $Kabutops = null;
	static $Horsea = null;
	static $Seadra = null;
	static $Sandshrew = null;
	static $Sandslash = null;
	static $Omanyte = null;
	static $Omastar = null;
	static $Jigglypuff = null;
	static $Wigglytuff = null;
	static $Eevee = null;
	static $Flareon = null;
	static $Jolteon = null;
	static $Vaporeon = null;
	static $Machop = null;
	static $Zubat = null;
	static $Ekans = null;
	static $Paras = null;
	static $Poliwhirl = null;
	static $Poliwrath = null;
	static $Weedle = null;
	static $Kakuna = null;
	static $Beedrill = null;
	static $Dodrio = null;
	static $Primeape = null;
	static $Dugtrio = null;
	static $Venomoth = null;
	static $Dewgong = null;
	static $Caterpie = null;
	static $Metapod = null;
	static $Butterfree = null;
	static $Machamp = null;
	static $Golduck = null;
	static $Hypno = null;
	static $Golbat = null;
	static $Mewtwo = null;
	static $Snorlax = null;
	static $Magikarp = null;
	static $Muk = null;
	static $Kingler = null;
	static $Cloyster = null;
	static $Electrode = null;
	static $Clefable = null;
	static $Weezing = null;
	static $Persian = null;
	static $Marowak = null;
	static $Haunter = null;
	static $Abra = null;
	static $Alakazam = null;
	static $Pidgeotto = null;
	static $Pidgeot = null;
	static $Starmie = null;
	static $Bulbasaur = null;
	static $Venusaur = null;
	static $Tentacruel = null;
	static $Goldeen = null;
	static $Seaking = null;
	static $Ponyta = null;
	static $Rapidash = null;
	static $Rattata = null;
	static $Raticate = null;
	static $Nidorino = null;
	static $Nidorina = null;
	static $Geodude = null;
	static $Porygon = null;
	static $Aerodactyl = null;
	static $Magnemite = null;
	static $Charmander = null;
	static $Squirtle = null;
	static $Charmeleon = null;
	static $Wartortle = null;
	static $Charizard = null;
	static $Oddish = null;
	static $Gloom = null;
	static $Vileplume = null;
	static $Bellsprout = null;
	static $Weepinbell = null;
	static $Victreebel = null;

	private $hexCode;
	private $name;

	public static $map;

	public function __construct($hexCode, $name) {
		$this->hexCode = $hexCode;
		$this->name = $name;
	}
	public static function init () {
		self::$Rhydon  	= new Species("0x01", "Rhydon");
		self::$Kangaskhan  	= new Species("0x02", "Kangaskhan");
		self::$NidoranM  	= new Species("0x03", "Nidoran♂");
		self::$Clefairy  	= new Species("0x04", "Clefairy");
		self::$Spearow  	= new Species("0x05", "Spearow");
		self::$Voltorb  	= new Species("0x06", "Voltorb");
		self::$Nidoking  	= new Species("0x07", "Nidoking");
		self::$Slowbro  	= new Species("0x08", "Slowbro");
		self::$Ivysaur  	= new Species("0x09", "Ivysaur");
		self::$Exeggutor  	= new Species("0x0A", "Exeggutor");
		self::$Lickitung  	= new Species("0x0B", "Lickitung");
		self::$Exeggcute  	= new Species("0x0C", "Exeggcute");
		self::$Grimer  	= new Species("0x0D", "Grimer");
		self::$Gengar  	= new Species("0x0E", "Gengar");
		self::$NidoranF  	= new Species("0x0F", "Nidoran♀");
		self::$Nidoqueen  	= new Species("0x10", "Nidoqueen");
		self::$Cubone  	= new Species("0x11", "Cubone");
		self::$Rhyhorn  	= new Species("0x12", "Rhyhorn");
		self::$Lapras  	= new Species("0x13", "Lapras");
		self::$Arcanine  	= new Species("0x14", "Arcanine");
		self::$Mew  	= new Species("0x15", "Mew");
		self::$Gyarados  	= new Species("0x16", "Gyarados");
		self::$Shellder  	= new Species("0x17", "Shellder");
		self::$Tentacool  	= new Species("0x18", "Tentacool");
		self::$Gastly  	= new Species("0x19", "Gastly");
		self::$Scyther  	= new Species("0x1A", "Scyther");
		self::$Staryu  	= new Species("0x1B", "Staryu");
		self::$Blastoise  	= new Species("0x1C", "Blastoise");
		self::$Pinsir  	= new Species("0x1D", "Pinsir");
		self::$Tangela  	= new Species("0x1E", "Tangela");
		self::$Growlithe  	= new Species("0x21", "Growlithe");
		self::$Onix  	= new Species("0x22", "Onix");
		self::$Fearow  	= new Species("0x23", "Fearow");
		self::$Pidgey  	= new Species("0x24", "Pidgey");
		self::$Slowpoke  	= new Species("0x25", "Slowpoke");
		self::$Kadabra  	= new Species("0x26", "Kadabra");
		self::$Graveler  	= new Species("0x27", "Graveler");
		self::$Chansey  	= new Species("0x28", "Chansey");
		self::$Machoke  	= new Species("0x29", "Machoke");
		self::$MrMime  	= new Species("0x2A", "Mr. Mime");
		self::$Hitmonlee  	= new Species("0x2B", "Hitmonlee");
		self::$Hitmonchan  	= new Species("0x2C", "Hitmonchan");
		self::$Arbok  	= new Species("0x2D", "Arbok");
		self::$Parasect  	= new Species("0x2E", "Parasect");
		self::$Psyduck  	= new Species("0x2F", "Psyduck");
		self::$Drowzee  	= new Species("0x30", "Drowzee");
		self::$Golem  	= new Species("0x31", "Golem");
		self::$Magmar  	= new Species("0x33", "Magmar");
		self::$Electabuzz  	= new Species("0x35", "Electabuzz");
		self::$Magneton  	= new Species("0x36", "Magneton");
		self::$Koffing  	= new Species("0x37", "Koffing");
		self::$Mankey  	= new Species("0x39", "Mankey");
		self::$Seel  	= new Species("0x3A", "Seel");
		self::$Diglett  	= new Species("0x3B", "Diglett");
		self::$Tauros  	= new Species("0x3C", "Tauros");
		self::$Farfetchd  	= new Species("0x40", "Farfetch'd");
		self::$Venonat  	= new Species("0x41", "Venonat");
		self::$Dragonite  	= new Species("0x42", "Dragonite");
		self::$Doduo  	= new Species("0x46", "Doduo");
		self::$Poliwag  	= new Species("0x47", "Poliwag");
		self::$Jynx  	= new Species("0x48", "Jynx");
		self::$Moltres  	= new Species("0x49", "Moltres");
		self::$Articuno  	= new Species("0x4A", "Articuno");
		self::$Zapdos  	= new Species("0x4B", "Zapdos");
		self::$Ditto  	= new Species("0x4C", "Ditto");
		self::$Meowth  	= new Species("0x4D", "Meowth");
		self::$Krabby  	= new Species("0x4E", "Krabby");
		self::$Vulpix  	= new Species("0x52", "Vulpix");
		self::$Ninetales  	= new Species("0x53", "Ninetales");
		self::$Pikachu  	= new Species("0x54", "Pikachu");
		self::$Raichu  	= new Species("0x55", "Raichu");
		self::$Dratini  	= new Species("0x58", "Dratini");
		self::$Dragonair  	= new Species("0x59", "Dragonair");
		self::$Kabuto  	= new Species("0x5A", "Kabuto");
		self::$Kabutops  	= new Species("0x5B", "Kabutops");
		self::$Horsea  	= new Species("0x5C", "Horsea");
		self::$Seadra  	= new Species("0x5D", "Seadra");
		self::$Sandshrew  	= new Species("0x60", "Sandshrew");
		self::$Sandslash  	= new Species("0x61", "Sandslash");
		self::$Omanyte  	= new Species("0x62", "Omanyte");
		self::$Omastar  	= new Species("0x63", "Omastar");
		self::$Jigglypuff  	= new Species("0x64", "Jigglypuff");
		self::$Wigglytuff  	= new Species("0x65", "Wigglytuff");
		self::$Eevee  	= new Species("0x66", "Eevee");
		self::$Flareon  	= new Species("0x67", "Flareon");
		self::$Jolteon  	= new Species("0x68", "Jolteon");
		self::$Vaporeon  	= new Species("0x69", "Vaporeon");
		self::$Machop  	= new Species("0x6A", "Machop");
		self::$Zubat  	= new Species("0x6B", "Zubat");
		self::$Ekans  	= new Species("0x6C", "Ekans");
		self::$Paras  	= new Species("0x6D", "Paras");
		self::$Poliwhirl  	= new Species("0x6E", "Poliwhirl");
		self::$Poliwrath  	= new Species("0x6F", "Poliwrath");
		self::$Weedle  	= new Species("0x70", "Weedle");
		self::$Kakuna  	= new Species("0x71", "Kakuna");
		self::$Beedrill  	= new Species("0x72", "Beedrill");
		self::$Dodrio  	= new Species("0x74", "Dodrio");
		self::$Primeape  	= new Species("0x75", "Primeape");
		self::$Dugtrio  	= new Species("0x76", "Dugtrio");
		self::$Venomoth  	= new Species("0x77", "Venomoth");
		self::$Dewgong  	= new Species("0x78", "Dewgong");
		self::$Caterpie  	= new Species("0x7B", "Caterpie");
		self::$Metapod  	= new Species("0x7C", "Metapod");
		self::$Butterfree  	= new Species("0x7D", "Butterfree");
		self::$Machamp  	= new Species("0x7E", "Machamp");
		self::$Golduck  	= new Species("0x80", "Golduck");
		self::$Hypno  	= new Species("0x81", "Hypno");
		self::$Golbat  	= new Species("0x82", "Golbat");
		self::$Mewtwo  	= new Species("0x83", "Mewtwo");
		self::$Snorlax  	= new Species("0x84", "Snorlax");
		self::$Magikarp  	= new Species("0x85", "Magikarp");
		self::$Muk  	= new Species("0x88", "Muk");
		self::$Kingler  	= new Species("0x8A", "Kingler");
		self::$Cloyster  	= new Species("0x8B", "Cloyster");
		self::$Electrode  	= new Species("0x8D", "Electrode");
		self::$Clefable  	= new Species("0x8E", "Clefable");
		self::$Weezing  	= new Species("0x8F", "Weezing");
		self::$Persian  	= new Species("0x90", "Persian");
		self::$Marowak  	= new Species("0x91", "Marowak");
		self::$Haunter  	= new Species("0x93", "Haunter");
		self::$Abra  	= new Species("0x94", "Abra");
		self::$Alakazam  	= new Species("0x95", "Alakazam");
		self::$Pidgeotto  	= new Species("0x96", "Pidgeotto");
		self::$Pidgeot  	= new Species("0x97", "Pidgeot");
		self::$Starmie  	= new Species("0x98", "Starmie");
		self::$Bulbasaur  	= new Species("0x99", "Bulbasaur");
		self::$Venusaur  	= new Species("0x9A", "Venusaur");
		self::$Tentacruel  	= new Species("0x9B", "Tentacruel");
		self::$Goldeen  	= new Species("0x9D", "Goldeen");
		self::$Seaking  	= new Species("0x9E", "Seaking");
		self::$Ponyta  	= new Species("0xA3", "Ponyta");
		self::$Rapidash  	= new Species("0xA4", "Rapidash");
		self::$Rattata  	= new Species("0xA5", "Rattata");
		self::$Raticate  	= new Species("0xA6", "Raticate");
		self::$Nidorino  	= new Species("0xA7", "Nidorino");
		self::$Nidorina  	= new Species("0xA8", "Nidorina");
		self::$Geodude  	= new Species("0xA9", "Geodude");
		self::$Porygon  	= new Species("0xAA", "Porygon");
		self::$Aerodactyl  	= new Species("0xAB", "Aerodactyl");
		self::$Magnemite  	= new Species("0xAD", "Magnemite");
		self::$Charmander  	= new Species("0xB0", "Charmander");
		self::$Squirtle  	= new Species("0xB1", "Squirtle");
		self::$Charmeleon  	= new Species("0xB2", "Charmeleon");
		self::$Wartortle  	= new Species("0xB3", "Wartortle");
		self::$Charizard  	= new Species("0xB4", "Charizard");
		self::$Oddish  	= new Species("0xB9", "Oddish");
		self::$Gloom  	= new Species("0xBA", "Gloom");
		self::$Vileplume  	= new Species("0xBB", "Vileplume");
		self::$Bellsprout  	= new Species("0xBC", "Bellsprout");
		self::$Weepinbell  	= new Species("0xBD", "Weepinbell");
		self::$Victreebel  	= new Species("0xBE", "Victreebel");


		self::$map = array (
			"Rhydon" => self::$Rhydon,
			"Kangaskhan" => self::$Kangaskhan,
			"NidoranM" => self::$NidoranM,
			"Clefairy" => self::$Clefairy,
			"Spearow" => self::$Spearow,
			"Voltorb" => self::$Voltorb,
			"Nidoking" => self::$Nidoking,
			"Slowbro" => self::$Slowbro,
			"Ivysaur" => self::$Ivysaur,
			"Exeggutor" => self::$Exeggutor,
			"Lickitung" => self::$Lickitung,
			"Exeggcute" => self::$Exeggcute,
			"Grimer" => self::$Grimer,
			"Gengar" => self::$Gengar,
			"NidoranF" => self::$NidoranF,
			"Nidoqueen" => self::$Nidoqueen,
			"Cubone" => self::$Cubone,
			"Rhyhorn" => self::$Rhyhorn,
			"Lapras" => self::$Lapras,
			"Arcanine" => self::$Arcanine,
			"Mew" => self::$Mew,
			"Gyarados" => self::$Gyarados,
			"Shellder" => self::$Shellder,
			"Tentacool" => self::$Tentacool,
			"Gastly" => self::$Gastly,
			"Scyther" => self::$Scyther,
			"Staryu" => self::$Staryu,
			"Blastoise" => self::$Blastoise,
			"Pinsir" => self::$Pinsir,
			"Tangela" => self::$Tangela,
			"Growlithe" => self::$Growlithe,
			"Onix" => self::$Onix,
			"Fearow" => self::$Fearow,
			"Pidgey" => self::$Pidgey,
			"Slowpoke" => self::$Slowpoke,
			"Kadabra" => self::$Kadabra,
			"Graveler" => self::$Graveler,
			"Chansey" => self::$Chansey,
			"Machoke" => self::$Machoke,
			"MrMime" => self::$MrMime,
			"Hitmonlee" => self::$Hitmonlee,
			"Hitmonchan" => self::$Hitmonchan,
			"Arbok" => self::$Arbok,
			"Parasect" => self::$Parasect,
			"Psyduck" => self::$Psyduck,
			"Drowzee" => self::$Drowzee,
			"Golem" => self::$Golem,
			"Magmar" => self::$Magmar,
			"Electabuzz" => self::$Electabuzz,
			"Magneton" => self::$Magneton,
			"Koffing" => self::$Koffing,
			"Mankey" => self::$Mankey,
			"Seel" => self::$Seel,
			"Diglett" => self::$Diglett,
			"Tauros" => self::$Tauros,
			"Farfetchd" => self::$Farfetchd,
			"Venonat" => self::$Venonat,
			"Dragonite" => self::$Dragonite,
			"Doduo" => self::$Doduo,
			"Poliwag" => self::$Poliwag,
			"Jynx" => self::$Jynx,
			"Moltres" => self::$Moltres,
			"Articuno" => self::$Articuno,
			"Zapdos" => self::$Zapdos,
			"Ditto" => self::$Ditto,
			"Meowth" => self::$Meowth,
			"Krabby" => self::$Krabby,
			"Vulpix" => self::$Vulpix,
			"Ninetales" => self::$Ninetales,
			"Pikachu" => self::$Pikachu,
			"Raichu" => self::$Raichu,
			"Dratini" => self::$Dratini,
			"Dragonair" => self::$Dragonair,
			"Kabuto" => self::$Kabuto,
			"Kabutops" => self::$Kabutops,
			"Horsea" => self::$Horsea,
			"Seadra" => self::$Seadra,
			"Sandshrew" => self::$Sandshrew,
			"Sandslash" => self::$Sandslash,
			"Omanyte" => self::$Omanyte,
			"Omastar" => self::$Omastar,
			"Jigglypuff" => self::$Jigglypuff,
			"Wigglytuff" => self::$Wigglytuff,
			"Eevee" => self::$Eevee,
			"Flareon" => self::$Flareon,
			"Jolteon" => self::$Jolteon,
			"Vaporeon" => self::$Vaporeon,
			"Machop" => self::$Machop,
			"Zubat" => self::$Zubat,
			"Ekans" => self::$Ekans,
			"Paras" => self::$Paras,
			"Poliwhirl" => self::$Poliwhirl,
			"Poliwrath" => self::$Poliwrath,
			"Weedle" => self::$Weedle,
			"Kakuna" => self::$Kakuna,
			"Beedrill" => self::$Beedrill,
			"Dodrio" => self::$Dodrio,
			"Primeape" => self::$Primeape,
			"Dugtrio" => self::$Dugtrio,
			"Venomoth" => self::$Venomoth,
			"Dewgong" => self::$Dewgong,
			"Caterpie" => self::$Caterpie,
			"Metapod" => self::$Metapod,
			"Butterfree" => self::$Butterfree,
			"Machamp" => self::$Machamp,
			"Golduck" => self::$Golduck,
			"Hypno" => self::$Hypno,
			"Golbat" => self::$Golbat,
			"Mewtwo" => self::$Mewtwo,
			"Snorlax" => self::$Snorlax,
			"Magikarp" => self::$Magikarp,
			"Muk" => self::$Muk,
			"Kingler" => self::$Kingler,
			"Cloyster" => self::$Cloyster,
			"Electrode" => self::$Electrode,
			"Clefable" => self::$Clefable,
			"Weezing" => self::$Weezing,
			"Persian" => self::$Persian,
			"Marowak" => self::$Marowak,
			"Haunter" => self::$Haunter,
			"Abra" => self::$Abra,
			"Alakazam" => self::$Alakazam,
			"Pidgeotto" => self::$Pidgeotto,
			"Pidgeot" => self::$Pidgeot,
			"Starmie" => self::$Starmie,
			"Bulbasaur" => self::$Bulbasaur,
			"Venusaur" => self::$Venusaur,
			"Tentacruel" => self::$Tentacruel,
			"Goldeen" => self::$Goldeen,
			"Seaking" => self::$Seaking,
			"Ponyta" => self::$Ponyta,
			"Rapidash" => self::$Rapidash,
			"Rattata" => self::$Rattata,
			"Raticate" => self::$Raticate,
			"Nidorino" => self::$Nidorino,
			"Nidorina" => self::$Nidorina,
			"Geodude" => self::$Geodude,
			"Porygon" => self::$Porygon,
			"Aerodactyl" => self::$Aerodactyl,
			"Magnemite" => self::$Magnemite,
			"Charmander" => self::$Charmander,
			"Squirtle" => self::$Squirtle,
			"Charmeleon" => self::$Charmeleon,
			"Wartortle" => self::$Wartortle,
			"Charizard" => self::$Charizard,
			"Oddish" => self::$Oddish,
			"Gloom" => self::$Gloom,
			"Vileplume" => self::$Vileplume,
			"Bellsprout" => self::$Bellsprout,
			"Weepinbell" => self::$Weepinbell,
			"Victreebel" => self::$Victreebel
        );
	}
	public static function get($element) {
        if($element == null)
            return null;
        return self::$map[$element];
    }
    public function getHex(){
    	return PokemonData::hex($this->hexCode);
    }

    public function getName(){
    	return $this->name;
    }
}
Species::init();